### ISSUE TITLE
Data usage policy

### ISSUE THREAD

**Issue by p16i** [codeforthailand/parliament-listening#17]
Related to #2 

As the annotations were done, and will be done by volunteers, the data should be open to the public. Formally, we should provide some sort of guideline or license for our data to ensure that will be used and distributed in a good manner.

**Comment by unnawut** [comment]
I'll do research on this and come up with some options.

**Comment by unnawut** [comment]
Generally this policy should be applicable for the whole codeforthailand org.

**Comment by p16i** [comment]
Thanks a lot!

**Comment by unnawut** [comment]
So I checked with Wikipedia, World Bank, Data.gov, Data.gov.uk, Data.go.th, and OpenStreetMap.

I would say _Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA)_ would be best for these reasons?

- People are generally familiar with Creative Commons licenses already
- Has ShareAlike restrictions, which does not restrict commercial use, but forces any improvements to be shared alike.

Also, this license would apply to data only. Code should be licensed separately.

My findings below...

-----

Note that these are the default licenses for each site with an "unless stated otherwise" clause.

**Creative Commons Attribution-ShareAlike 3.0 Unported (CC BY-SA) ([license](https://creativecommons.org/licenses/by-sa/3.0/))**
- You are free to: Share, Adapt
- As long as you: Attribute, ShareAlike
- Used by: [Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Copyrights)

**Creative Commons Attribution 4.0 International (CC-BY 4.0) ([license](https://creativecommons.org/licenses/by/4.0/))** 
- You are free to: Share, Adapt
- As long as you: Attribute
- Used by [World Bank Data Catalog](https://datacatalog.worldbank.org/public-licenses) and [World Bank Open Data](https://data.worldbank.org/summary-terms-of-use)

**Open Government Licence v3.0 ([license](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/))**
- You are free to: Share, Create, Adapt
- As long as you: Attribute
- Used by [data.gov.uk](https://data.gov.uk/about)

**DGA Open Government License ([license](https://data.go.th/TermsAndConditions.aspx))**
- You are free to: Share, Create, Adapt
- As long as you: Attribute
- Used by: [Data.go.th](https://data.go.th/TermsAndConditions.asp)

**Open Database License (ODbL) version 1.0 ([license](https://opendatacommons.org/licenses/odbl/summary/index.html))**
- You are free to: Share, Create, Adapt
- As long as you: Attribute, Share-Alike, Keep open
- Used by: [OpenStreetMap](https://wiki.openstreetmap.org/wiki/Open_Database_License)

Remark: Data.gov doesn't really have a proper license but it says it's [offered free and without restriction](https://www.data.gov/privacy-policy#license).

**Comment by p16i** [comment]
Hi,

Thanks a lot. I think we can go with CC-BY-SA. How should we announce this? 

What do you think if we add CC-BY-SA's icon in README.md?

**Comment by unnawut** [comment]
Yeah readme should be good. Since there should be separate licenses between data and code, but we have them in the same repo. How about also these?

1. Put CC-BY-SA icon in README like you mentioned, but also mention it is for data.
2. Mention code is licensed under MIT in README too
3. Put license notice in the working spreadsheet
4. Put CC-BY-SA text in a LICENSE file in `/static/data`

I can do all those 4. Just need a second opinion before doing so.

**Comment by p16i** [comment]
sounds good to me!
